parameters:
  number: ["1", "2"]

jobs:
  - ${{ each number in parameters.number }}:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        displayName: Push artifact ${{ number }}
        steps:
          - checkout: none

          - bash: echo "${{ number }}" >> file_${{ number }}
            displayName: "Create file"

          - publish: "file_${{ number }}"
            displayName: "Publish file"
            artifact: "artifact-name"
