parameters:
  number: ["1", "2"]

jobs:
  - ${{ each number in parameters.number }}:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        displayName: Push artifact ${{ number }}
        steps:
          - checkout: none

          - bash: echo "${{ number }}" >> file_${{ number }}
            displayName: "Create file"

          - bash: |
              hash=$(echo ${{number}} | sha256sum | cut -d " " -f 1 | cut -c 1-7)
              echo $hash
              echo "##vso[task.setvariable variable=hash]$hash"
            displayName: "File name"

          - bash: |
              echo $(hash)
              cp file_${{ number }} file_$(hash)
            displayName: "Rename file"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: file_$(hash)
