parameters:
  number: ["1", "2"]

jobs:
  - ${{ each number in parameters.number }}:
      - job: job-${{ number }}
        displayName: Push artifact ${{ number }}
        steps:
          - checkout: none

          - bash: echo "${{ number }}" >> file_${{ number }}
            displayName: "Create file"

          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: file_${{ number }}
            displayName: "Publish artifact"

  - job:
    displayName: Download artifacts
    dependsOn:
      - ${{ each number in parameters.number }}:
        - job-${{ number }}
    steps:
      - checkout: none

      - task: DownloadPipelineArtifact@2
        inputs:
          patterns: file_*
        displayName: "Download docs artifact"

      - bash: ls -la
        displayName: "List files"
