jobs:
  - job:
    pool:
      vmImage: "ubuntu-latest"
    displayName: Upload to Codecov
    steps:
      # Checkout simpeg repo. Codecov needs the repo in the file system for
      # uploading coverage reports.
      - checkout: self
        displayName: "Checkout repository"

      - task: UsePythonVersion@0
        displayName: "Setup Python"

      - bash: |
          pip install coverage
        displayName: "Install coverage"

      - task: DownloadPipelineArtifact@2
        inputs:
          patterns: "**/coverage-*"
        displayName: "Download coverage artifacts"

      - bash: ls -la $(Pipeline.Workspace)/**/coverage-*
        displayName: "List downloaded coverage artifacts"

      - bash: |
          coverage combine $(Pipeline.Workspace)/**/coverage-*
          ls -la
        displayName: "Combine coverage reports"

      - bash: |
          coverage xml
          ls -la
        displayName: "Convert coverage report to xml"

      - script: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --verbose upload-process
        displayName: "Upload coverage to codecov.io"
