jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    displayName: Upload to Codecov
    steps:
      - checkout: none

      - download: current
        patterns: "**/coverage-*"

      - bash: ls -la $(Pipeline.Workspace)
        displayName: "List files"

      - bash: ls -la $(Pipeline.Workspace)/**/coverage-*
        displayName: "List files"

      - bash: cp $(Pipeline.Workspace)/coverage-*/coverage-* .
        displayName: "Copy files"

      - bash: ls -la
        displayName: "List files"


      - script: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
        displayName: "Install codecov"

      - script: |
          for report in coverage-*; do
            ./codecov upload-process -f "$report"
          done
        displayName: 'Upload coverage to codecov.io'
