jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    displayName: Upload to Codecov
    steps:
      - download: current
        patterns: "**/coverage-*.xml"

      - bash: ls -la $(Pipeline.Workspace)
        displayName: "List files"

      - bash: ls -la $(Pipeline.Workspace)/**/coverage-*.xml
        displayName: "List files"

      - bash: cp $(Pipeline.Workspace)/coverage-*/coverage-*.xml .
        displayName: "Copy files"

      - bash: ls -la
        displayName: "List files"

      - script: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
        displayName: "Install codecov"

      - script: |
          for report in coverage-*.xml; do
            ./codecov --verbose upload-process -f "$report"
          done
        displayName: 'Upload coverage to codecov.io'
