jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    displayName: Download artifacts
    steps:
      - checkout: none

      # - task: DownloadPipelineArtifact@2
      #   inputs:
      #     artifact: file_1
      #     # patterns: "**/file_*"

      - download: current
        patterns: "**/file_*"

      - bash: ls -la
        displayName: "List files"

      - bash: ls -la $(Pipeline.Workspace)
        displayName: "List files"

      - bash: ls -la $(Pipeline.Workspace)/file_1
        displayName: "List files"

      - bash: ls -la $(Pipeline.Workspace)/file_2
        displayName: "List files"
